Version: '1.0.0'
Food: 'Potato'
FoodList:
  - 'apple'
  - 'orange'
  - 'grape'

on-message: "&6你开开启了飞行模式"
off-message: "&7你关闭了飞行模式"

##奥术之弓配置
bow-name: "Arcane bow"
bow-description: "发射一个传送箭矢"
give-bow-on-join: true

##盔甲架模块配置
create-message: '&6生成盔甲架'
delete-message: '&c删除盔甲架预设'
confirm-option: '&a选项确认'
cancel-option: '&c选项取消'
added: '&a添加'
delete: '&c取消添加'